### ISSUE TITLE
Feature: add keyboard shortcut to go to context menu

### ISSUE THREAD

**Issue by jjw24** [jjw24/Wox#102]
Add keyboard shortcut to go to context menu. Current behaviour requires using the mouse then right clicking. Add something like Alt + Enter to go to context menu on a result~ hands on keyboard still

**Comment by theClueless** [comment]
It already exists, you can use Ctrl+O.
These are all the shortcuts in the application:
![image](https://user-images.githubusercontent.com/14300910/70760619-e97c9080-1d52-11ea-9b33-5b1f606348d5.png)

**Comment by jjw24** [comment]
:man_facepalming: lol all these time I been using the mouse. Should we expose it somehow in the application? I remember seeing some issue upstream where some users don't know how to go back from context menu.

**Comment by duurland** [comment]
https://github.com/Wox-launcher/Wox/wiki/Getting-started.-Usage#contextual-menu

**Comment by jjw24** [comment]
> https://github.com/Wox-launcher/Wox/wiki/Getting-started.-Usage#contextual-menu

Thanks for that, good to know. I was wondering more whether we should add the shortcut menu in the settings window and allow users to customise to their own liking rather than having to look for these kind of shortcuts somewhere else.
