### ISSUE TITLE
Example: Plugin written in nodejs

### ISSUE THREAD

**Issue by duurland** [jjw24/Wox#110]
Hello.

I made a basic example of how to create plugins in nodejs.
Posting it here in case anyone might need it in the future.

https://github.com/duurland/Wox.Plugin.HelloWorldNodeJS

Cheers

**Comment by jjw24** [comment]
Reopening this issue if it is OK, because I think it would be good idea to integrate this into Wox along with the C sharp and Python example projects.

**Comment by jjw24** [comment]
Just going to close this as this repo is no longer maintained, feel free to open the issue in Flow if this is still a problem
