### ISSUE TITLE
"Should Use Pinyin" option is useless

### ISSUE THREAD

**Issue by popdisk** [jjw24/Wox#111]
### Are you submitting a bug report?

Yes.
I couldn't search items by Pinyin with the "Should Use Pinyin" option selected while it works normal in the original version.

### Steps to reproduce

1.Type "ditu" in Wox and it shows unrelated results.
2.Type "地图" and it goes right.

### Screenshots (optional)
![image](https://user-images.githubusercontent.com/30627205/71544313-c855aa00-29b8-11ea-970c-ef339c8b313a.png)
![image](https://user-images.githubusercontent.com/30627205/71544317-d86d8980-29b8-11ea-9f29-5dfa7370078f.png)

**Comment by jjw24** [comment]
Let me check out this bug and get back to you

**Comment by HsunGong** [comment]
This is a bug that occurs in my app.

**Comment by jjw24** [comment]
Fixed in #131
