### ISSUE TITLE
The JSON-RPC 2.0 Specification

### ISSUE THREAD

**Issue by duurland** [jjw24/Wox#113]
In the docs it's said that Wox use the [JSON-RPC Spec](https://www.jsonrpc.org/specification) to communicate with its plugins, however, it doesnt seem to actually follow the specification.

A valid request to a plugin, according to the spec, looks like this

```JSON
{
    "jsonrpc": "2.0",
    "method": "query",
    "params": ["hello world"],
    "id": 1
}
```
This is the payload our plugins currently get from Wox

```JSON
{
    "method": "query",
    "parameters": ["hello world"],
}
```

The only part Wox actually got right is the `method` key.

`jsonrpc`: While I can see why this can be omitted, I don't think it's a bad idea to be explicit about what protocol is being used when communicating with other plugins/processes, specially for future backward compatibility.

`params`: The specs and Woxs doc both mention the `params` key for the parameters, but for some reason the actual payload use `parameters` instead.

`id`: All requests that expects a response (ie the `query` function) should include an ID, which should also be sent back in the response along with the result. This is currently omitted.

The specs also mention an `error` key in our response, but as far as I can tell that data is also being ignored.

**Comment by jjw24** [comment]
Just going to close this as this repo is no longer maintained, feel free to open the issue in Flow if this is still a problem
