### ISSUE TITLE
Feature: Recent results list

### ISSUE THREAD

**Issue by jjw24** [jjw24/Wox#116]
Show recent results when activated and query textbox is blank.
- give user option to turn this on
- should show query results in history not actual query typed when hit ctrl h
- query result history is ordered by most used

**Comment by HsunGong** [comment]
- I find `ctrl+h` works by default, but I have never known this before.

- What you mean `query box is blank` ? 
Do you mean that, after `ctrl-h`, can not filter results when input some query?
![image](https://user-images.githubusercontent.com/32933986/71875729-f2009500-315f-11ea-8cd8-a58e56f1fd47.png)

- I find the query order is set by time-used default. 
Maybe this can be extended into a plugin? 

1. So we can choose which order can be used.
2. We can choose it is on/off.
3. change hotkey if we used(not use `ctrl-h` anymore), but register keywords, and we can register `ctrl-h` if we need.

**Comment by jjw24** [comment]
Query history is OK, I was thinking more of result history, show some of the most commonly used results (not actual queries as you get with ctrl h). Like the recent list in Windows.

What I mean by when query box is blank is when you activate wox, and if there no query text, then show the most used recent results. 

Ultimately to reduce the number of times I need to type again for the same result I used in the past.
