### ISSUE TITLE
Feature: Folder plugin- show folder location for results when using wildcard

### ISSUE THREAD

**Issue by jjw24** [jjw24/Wox#118]
Quite often when using wildcard '>', would be getting duplicate folder names that resides in different locations, will be useful to know the path they reside in so to choose the correct result.

**Comment by theClueless** [comment]
do you mean when you use the ">" wildcard\ saved folders? because otherwise you always know the location, right?

**Comment by jjw24** [comment]
> do you mean when you use the ">" wildcard\ saved folders? because otherwise you always know the location, right?

Yes that's right, will update description.
