### ISSUE TITLE
FuzzySearch character matching

### ISSUE THREAD

**Issue by jjw24** [jjw24/Wox#132]
![image](https://user-images.githubusercontent.com/26427004/72663034-08e99600-3a42-11ea-8211-59892d161605.png)

Context:
If I type "test" to search for "the book on automated software testing", score is not high enough. Sub-string matching is ignored due to already fully matching characters "[**t**]h[**e**] book on automated [**s**]of[**t**]ware testing"

**Comment by HsunGong** [comment]
One thing I am curious about, If I type `termina`, no `Windows terminal` results returned. Although the score might be low, should not this result appear?

![image](https://user-images.githubusercontent.com/32933986/73623420-df528080-4677-11ea-87f7-1641a2d78880.png)


![image](https://user-images.githubusercontent.com/32933986/73623410-d5308200-4677-11ea-8694-90b29739f4bc.png)

**Comment by jjw24** [comment]
Just going to close this as this repo is no longer maintained, feel free to open the issue in Flow if this is still a problem
