### ISSUE TITLE
Display Wox on Key-Up instead Key-Down

### ISSUE THREAD

**Issue by skjerns** [jjw24/Wox#138]
I have the Windows key as a hotkey for Wox.

However, it always pops up on key-down when I do any other Windows-hotkey (win+r, win+d, ...).

This is just a cosmetic issue, as it dissapears after I press the hotkey. Still, I would like to know if there is a setting to activate Wox only on key up and if there is no other hotkey, and not on key-down.

**Comment by jjw24** [comment]
Just so I am clear, your hot key set up is using only the windows key as the activation for Wox?

**Comment by skjerns** [comment]
Exactly! My I disabled that the Windows-Key using [OpenShellMenu](https://github.com/Open-Shell/Open-Shell-Menu), then re-assigned it to Wox (I'm using Start anyway only to open apps and Wox is faster).

Then if I press the Win-Key, immediately Wox pops up, on key-down, even if I want to do another hotkey.

This is the same also with other keys assigned: E.g if I assign it to f12 and make the fictious hotkey F12+D, Wox pops up when I press F12 already.

**Comment by theClueless** [comment]
@jjw24 After some light reading, the only way to do that is to stop using Nhotkey lib and start doing a more low level hooking that will listen to all key events in windows.
So this is doesn't seem like a trivial issue :|

**Comment by jjw24** [comment]
> Exactly! My I disabled that the Windows-Key using [OpenShellMenu](https://github.com/Open-Shell/Open-Shell-Menu), then re-assigned it to Wox (I'm using Start anyway only to open apps and Wox is faster).
> 
> Then if I press the Win-Key, immediately Wox pops up, on key-down, even if I want to do another hotkey.
> 
> This is the same also with other keys assigned: E.g if I assign it to f12 and make the fictious hotkey F12+D, Wox pops up when I press F12 already.

Interesting usage. A brief playing around with the hotkeys I found I am not able to set combo with Win-Key or the F keys, only Alt, Ctrl and Shift keys.

I am keen on seeing this capability made, hopefully someone down the track can put in a PR for this, but as @theClueless has indicated, this may not be a quick change.

**Comment by skjerns** [comment]
Okay, no problem.

Setting the Windows key as Wox is only possible after disabling the Winkey with ClassicalShell

**Comment by jjw24** [comment]
Issue transferred to Flow and will be addressed in the future
