### ISSUE TITLE
Everything service is not running

### ISSUE THREAD

**Issue by 0xbs0d** [jjw24/Wox#140]
### Are you submitting a bug report?
Yes
(write your answer here)

### Steps to reproduce

1. installed everything search as a service
2. downloaded last version of Wox portable
3. ran Wox and activated the everything plugin
4. getting the error: Everything service is not running

### Wox Error Window text

(paste here)

### Detailed logs

(drop your log file here)

### Screenshots (optional)

(drop your screenshot here)

**Comment by jjw24** [comment]
Hey how's it going.

Which version of everything search you are using? I tested the portable version with everything downloaded from the upstream repo here(64bit): https://github.com/Wox-launcher/Wox/releases/download/v1.3.524/Everything-1.3.4.686.x64-Setup.exe

Seems to working. Let me know how you go (obviously need to enable the plugin in Wox's settings and make sure the everything service is running in Services).

**Comment by 0xbs0d** [comment]
Hey! Thank you for your reply. I was using Everything 1.4.x but with the version you linked everything works correctly. Since I don't see many advantages of using the latest version of Everything I'm good with using the version you suggested. 
Thank you for your help! :)
