### ISSUE TITLE
Ram usage

### ISSUE THREAD

**Issue by thegamerx1** [jjw24/Wox#161]
### Are you submitting a bug report?
yes

### Steps to reproduce
1.start wox
2.open task manager
3.check ram

### Detailed logs
https://pastebin.com/djYczW8F

i think that 100mb is too much for a launcher
![image](https://user-images.githubusercontent.com/34986564/76236495-0e3ab400-622d-11ea-84b9-818d16d401a6.png)

**Comment by jjw24** [comment]
hmm, we have had a similar issue with this in https://github.com/jjw24/Wox/issues/96, likely also due to image caching. Will take a look later. My process usually averages between 70-80 mbs.

**Comment by theClueless** [comment]
the image caching is still not optimal, It would be fairly simple to reduce the load and pay a little bit in the time it take to show the icons.
Simple solution would be to make the MaxCached = 5000 const value in ImageCache to a configurable of low (500)\med (3000)\high (5000) memory usage.
Another better option is to try and see how we load it faster and fully remove it better from memory after usage.
I wanted to get to it but still didn't got the chance.
3 main we can start with are:
- I still think we leak a little memory when we try to dispose of the image.
- we keep loading folder icons (to verify it is not a special icon for that folder) and this could be done in a much more efficient way.
- we could probably load the images in a faster manner to reduce the load.
some helpful links I gathered - 
	- Images stuff - 
		○ Extracting shell icons - 
			§ https://hypercoder.com/extracting-shell-icons-and-thumbnails-wpf/
		○ https://social.msdn.microsoft.com/Forums/vstudio/en-US/3d47d440-d5f2-4149-8d14-3e3d35e606a7/convert-interopbitmap-to-bitmapimage?forum=wpf
		○ https://stackoverflow.com/questions/6484357/converting-bitmapimage-to-bitmap-and-vice-versa - convert images
		○ https://social.msdn.microsoft.com/Forums/vstudio/en-US/a2a334dc-2f1a-4ec0-9b99-ed96292f3cdb/bitmapimage-from-bitmapsource?forum=wpf - > bitmap image from bitmap source
		○ https://social.msdn.microsoft.com/Forums/vstudio/en-US/2cc3064a-cd70-4802-8e8b-6daa6c0e7c68/undisposed-bitmapsourcesafemilhandle-instances?forum=wpf
		○ https://www.pcreview.co.uk/threads/bitmapsourcesafemilhandle-safemilhandle-never-disposed.3655904/
		○ https://stackoverflow.com/questions/4567328/create-thumbnails-of-images-and-store-them-in-cache
		○ Memory links - 
			§ https://stackoverflow.com/questions/10981179/wpf-createbitmapsourcefromhbitmap-memory-leaks
		○ Check if folder have a special icon - 
			§ https://stackoverflow.com/questions/23666076/how-to-get-the-icon-associated-with-a-specific-folder (method in Wox)
			§ Getting the posiiton of the icon in order not to load it - 
				□ https://social.msdn.microsoft.com/Forums/en-US/bf403688-c664-4641-9fba-88fbd1d08613/getting-icon-position-from-shell?forum=csharpgeneral
			§ https://stackoverflow.com/questions/13295728/how-to-determine-if-folder-has-custom-icon
			§ An imp - 
				□ https://github.com/jemagoga/ank_git/blob/master/src/Ankh.VS/SolutionExplorer/FileIconMapper.cs
			§ Docs about the windows class to get it (unmanged)
			§ Example - 
				□ https://social.msdn.microsoft.com/Forums/en-US/60610aff-2dfd-4d52-9c4d-638d514100d0/calling-shgetfileinfo-in-c-win-x64?forum=netfxbcl

**Comment by jjw24** [comment]
Just going to close this as this repo is no longer maintained, feel free to open the issue in Flow if this is still a problem
