### ISSUE TITLE
FEATURE > Include Windows Search Index

### ISSUE THREAD

**Issue by RalfRoemling** [jjw24/Wox#166]
Imo would be great to have a plugin that can use the windows index, 'cause it's containing not only filenames but content and meta-infos too.

**Comment by jjw24** [comment]
Do you mean a plugin that can display the metadata about the selected file?

**Comment by RalfRoemling** [comment]
No, that wasn't exactly what I meant. I try to explain: 

When you open `Windows Indexing-Options > Advanced > File Types` you can choose in which way the Windows Search Provider may index the files. Options are `FileProperties` only or `FileProperties and Content` 

You already can access WindowsSearch via Win-Key and start typing. 

For convenience and clarities sake it'll be great to have this search built into Wox in parallel to the ultrafast Everything Search Provider

**Comment by jjw24** [comment]
This new plugin has been added to the new launcher which searches files and folders using Windows Indexing. The remaining suggestions- searching via content and meta-infos can be added later on.

**Comment by RalfRoemling** [comment]
Hi Jeremy, 
thx for including this feature. Do  I get this right that you've moved jjw24/wox to Flow? Will it be available in the jjw24 updates as well or solely on Flow?

**Comment by jjw24** [comment]
Hey how's it going. Right now this will only be available in Flow. In the future JJW24/Wox will be upgrade to Flow so everyone else here will get it as well.

**Comment by RalfRoemling** [comment]
I'm fine thx, hope you too :-)

Great to hear that there'll be an automated crossgrade. Would you recommend movin' over at the moment or is Flow more like "work in progress"?

**Comment by jjw24** [comment]
> I'm fine thx, hope you too :-)
> 
> Great to hear that there'll be an automated crossgrade. Would you recommend movin' over at the moment or is Flow more like "work in progress"?

I am doing good thank you :)

All functionalities are working great at the moment with Flow, only downside is that it is yet to support non-default Wox plugins(the ones you download), we will still have to work on that.

If you are only using the default plugins that are embedded currently with JJW/Wox installation, then you are good to move over to Flow. You will need to manually copy the settings files over but it's not too complicated to do. 

Have said this, if you have a plugin that you find is very useful, you can let me know in the Flow repo and I will look to migrate it(can't guarantee straightaway but will do so within a timeframe).
