### ISSUE TITLE
请问和原版wox的区别是什么？

### ISSUE THREAD

**Issue by zhaoliang0302** [jjw24/Wox#167]
我看安装包体积更大了，不知道改进了哪些方面。
还有，alt+space调出搜索框时光标不会聚焦到搜索框，打字出现在桌面，必须要点一下搜索框输入才行
感谢！

操作系统win10 LTSC，x64

**Comment by jjw24** [comment]
Hi @zhaoliang0302, 和原版的区别有很多，尤其增加了去多新功能比如移动版本，管理运行软件，提高了搜索的体验，和修复了许多Wox本身问题。
**ReadMe**里包括：

“

- Portable mode
- Drastically improved search experience
- Search all subfolders and files
- Option to always run CMD or Powershell as administrator
- Run CMD, Powershell and programs as a different user
- Manage what programs should be loaded
- Highlighting of how results are matched during query search
- Open web search result as a tab or a new window
- Automatic update
- Reload/update plugin data

”

**Comment by jjw24** [comment]
> 还有，alt+space调出搜索框时光标不会聚焦到搜索框，打字出现在桌面，必须要点一下搜索框输入才行
> 感谢！
> 
> 操作系统win10 LTSC，x64

应该不需要点一下才能输入。唯一要点是刚安装完启动的那一次，后面调出应该可以直接输入。如果一直这样你可以开启Windows Sandbox 试下还是不是这样。（我也是Win10）。

**Comment by zhaoliang0302** [comment]
非常感谢！listary有一个功能非常好用，左键双击可以快速进入收藏文件夹，尤其是下载选目标文件夹时候。能否考虑增加这个功能呢？

**Comment by jjw24** [comment]
Folder 插件可以让你在设置那里增加收藏文件夹,不知道和你说的功能一不一样。

listary 我还没用过，所以不清楚你说的功能，不过你可以开个issue 把那你想增加的功能写给我们，附上图片。如果可以的话附带英文，因为这里的contributor可能不懂中文。

**Comment by jjw24** [comment]
关闭此issue。如果还需要讨论欢迎重新打开，也可以新开个issue 说明你想增加的功能。

Closing this issue. Happy to reopen if further discussions required. For the feature suggested here please open a new one should you want to add in with proper outline of it.
