### ISSUE TITLE
Possible improvement for the Web Searches Plugin

### ISSUE THREAD

**Issue by hugolowegren** [jjw24/Wox#169]
The Web Searches plugin has a feature where a user could select a custom icon for a search query.
The location of such an image is seemingly restricted to "Local\Wox\app-xxx\Plugins\Wox.Plugins\WebSearch\Images", as it shows an error if there is an attempt to use another location. 

This becomes a problem when updating the application as that folder is replaced, removing all possible custom icon images with it. Meaning the end user would have to regularly back them up and restore them after an update.

I would assume one possible solution to this would be to have the plugin also read icon files from a folder within the "Roaming\Wox" directory instead, such as the already existing "Roaming\Wox\Settings\Plugins\Wox.Plugin.WebSearch" or "Roaming\Wox\Plugins".

This is for version 1.46.22 NON-Portable.

**Comment by theClueless** [comment]
@jjw24 why do we restrict it? I don't see any issue with the user specifying any icon.
Can we maybe just open it?

**Comment by jjw24** [comment]
@HugoLowegren @theClueless agree I don't see why we would just restrict it to that location and yes will get wiped during the update. @HugoLowegren good catch and suggestion. 

When we change it to open it up though, we need to consider portable mode so maybe either only allow location from the userdata location(local or roaming) where the rest of the user configs are stored, or remind users to copy the icons when they choose portable mode.

**Comment by jjw24** [comment]
This is already done in Flow Launcher
