### ISSUE TITLE
Icons not displaying

### ISSUE THREAD

**Issue by Queuecumbr** [jjw24/Wox#170]
### Are you submitting a bug report?

Yes

### Steps to reproduce

Icons are not displaying for Wox plugins. Custom icons are not displaying for Control Panel related actions.

Steps to reproduce;

1. Start Wox
2. Press hotkey
3. Search for anything that would bring up an icon provided with Wox such as any custom Control Panel Icons or any icons located in %USERPROFILE%\AppData\Local\Wox\app-1.47.22\Images\

or

1. Start Wox
2. Open Wox Settings
3. Go to plugins tab

### Wox Error Window text

No error windows are displaying. Only am able to see the symptoms.

### Detailed logs

[2020-03-19.txt](https://github.com/jjw24/Wox/files/4353298/2020-03-19.txt)

### Screenshots (optional)

![List](https://user-images.githubusercontent.com/11492746/77045072-25dd0f80-6986-11ea-9dcd-89254d20a74f.png)

![Settings](https://user-images.githubusercontent.com/11492746/77045163-46a56500-6986-11ea-8700-f15d61603a66.png)

**Comment by jjw24** [comment]
The log is showing UnauthorizedException to the app data Wox folder. Can you check the permission on the folder please.

**Comment by Queuecumbr** [comment]
I figured out the issue. The permissions were all set correctly. The program Icaros was just causing issues since it can be used to cache thumbnails. Once I disabled it from caching JPGs and PNGs, the icons started showing up like normal.
