### ISSUE TITLE
Portable mode

### ISSUE THREAD

**Issue by vivadavid** [jjw24/Wox#175]
Hello,

In the latest version, 1.50.23, there's a new feature called _portable mode_. By enabling it, I was expecting Wox to let me select a folder to keep all the files and settings, but that wasn't the case and I haven't noticed a difference between normal and portable modes.

The way I understand portability involves having all the files and settings of a programme in a folder that you've selected and that is located in a path known by you, so you can copy everything and move it to a different computer.

The old approach where you could download the ZIP file with the portable version was perfectly fine to me. I wonder why this change was made.

Thank you for your time and sorry if I'm asking about something obvious.

**Comment by JustACuteGirlLookingForAManToFixHerBugs** [comment]
So, my understanding is that it moves everything from ROAMING to LOCAL folder under your username. And presumably you can now move this folder wherever you want... Gonna test this soon. 

BTW, I managed to break it by enabling and disabling portable mode a couple of times - and so all my settings were nulled to default. Original setting files were still available in the Roaming folder.

**Comment by jjw24** [comment]
> Hello,
> 
> In the latest version, 1.50.23, there's a new feature called _portable mode_. By enabling it, I was expecting Wox to let me select a folder to keep all the files and settings, but that wasn't the case and I haven't noticed a difference between normal and portable modes.
> 
> The way I understand portability involves having all the files and settings of a programme in a folder that you've selected and that is located in a path known by you, so you can copy everything and move it to a different computer.
> 
> The old approach where you could download the ZIP file with the portable version was perfectly fine to me. I wonder why this change was made.
> 
> Thank you for your time and sorry if I'm asking about something obvious.

Hi @vivadavid so when enabled, it removes start menu, desktop and startup shortcuts, and removes the uninstaller entry  for Wox. As a final act it will restart and move your roaming user data folder (%userprofile%\AppData\Roaming\Wox) into the Wox's program folder. 

Likewise when disabled, it will reinstate the above.

The Wox program folder is located at %userprofile%\AppData\Local, this is where the default location of where Wox is installed. So when you have it enabled, you can then move that folder around (obviously exit Wox first), and run it from any other location. It is like your previous zipped download.

This is a great question, obviously I work on Wox so I would naturally know where Wox is installed, so do you think after enabling portable mode a prompt to tell the user where the Wox folder is would be nicer or directly open up the Wox program location?

**Comment by jjw24** [comment]
> BTW, I managed to break it by enabling and disabling portable mode a couple of times - and so all my settings were nulled to default. Original setting files were still available in the Roaming folder.

haha ok do tell, how you break it @Satyrars? Did you wait for it to fully finish including restarting then trigger disable again or did you do the repetitive tick untick without waiting?

**Comment by JustACuteGirlLookingForAManToFixHerBugs** [comment]
>So, my understanding is that it moves everything from ROAMING to LOCAL folder under your username. And presumably you can now move this folder wherever you want... Gonna test this soon.

Yep, can confirm that putting the wox folder into a cloud works & syncs the settings on both computers.

>haha ok do tell, how you break it @Satyrars? Did you wait for it to fully finish including restarting then trigger disable again or did you do the repetitive tick untick without waiting?

Well, I've read somewhere that repetitive clicking makes it copy faster. Or Wox doesn't support this feature yet? **˚ ̆ ˚**
No-no, I've properly waited till it launches back - but nvm for now, it's way more likely it's something on my end. 

> Wox is installed, so do you think after enabling portable mode a prompt to tell the user where the Wox folder is would be nicer or directly open up the Wox program location?

I think, the best way would be to prompt user where he wants to put the portable folder (at least, I've expected this behaviour). But a prompt with something like "Hey, your folder is here now. You can move it anywhere you want (but close wox repetitively first)" will do.

**Comment by vivadavid** [comment]
@jjw24 , thank you for the thorough answer.

I think it'd be nice if users could get a prompt with a link to access the Wox folder. Directly opening up the Wox folder would be good too.  

Like MyGFHasBigTitsAndYouAreStillAVirginHaHa (thank you for your explanation), I was expecting Wox to ask me where I wanted to save Wox, but the workaround above should be helpful enough.

**Comment by jjw24** [comment]
@vivadavid @JustACuteGirlLookingForAManToFixHerBugs PRed. Thank you for your suggestion.
