### ISSUE TITLE
Multiple duplicates of programs

### ISSUE THREAD

**Issue by Ok23** [jjw24/Wox#177]
I suggest to add option to filter duplicates links of programs (and possible prefer links from start menu)

**Comment by jjw24** [comment]
Hi how's it going, this feature already exists, you can do it via Program plugin or using shift+enter to go to the program's context menu and disable it there:

![image](https://user-images.githubusercontent.com/26427004/78297651-c08b4000-757b-11ea-9db9-b401e825e123.png)

![image](https://user-images.githubusercontent.com/26427004/78297697-dac51e00-757b-11ea-8c4a-2d93e7906a95.png)

**Comment by Ok23** [comment]
But if you are a thousands links, it's maybe boring. Meybe do it automatic for identical links ?

**Comment by jjw24** [comment]
> But if you are a thousands links, it's maybe boring. Meybe do it automatic for identical links ?

They shouldn't be 100% identical, usually their path is different, in this scenario you can choose just to index the start menu and not the registry.

Can you screenshot what you mean?

**Comment by Ok23** [comment]
Yes path is different, but if 2 links absolutly identical but different path's it's shouldn't it be filtered ? I have folder on Desktop (which i indexing) where i store links, and same as start menu have links to same programs which duplicated in suggestions

**Comment by jjw24** [comment]
> Yes path is different, but if 2 links absolutly identical but different path's it's shouldn't it be filtered ? I have folder on Desktop (which i indexing) where i store links, and same as start menu have links to same programs which duplicated in suggestions

In this case couldn't you untick 'index start menu' in settings or have the desktop folder(assuming it should be a custom index location you added) not have the same shortcut as start menu?

**Comment by Ok23** [comment]
Not an option, in start menu there's a lot of standart programs, which i not nowhere to store. Ok this is only suggestion to add filtering identical links, thanks, i close issue
