### ISSUE TITLE
How can I use Python to make plugin has GUI？

### ISSUE THREAD

**Issue by Zeroto521** [jjw24/Wox#178]
Just like below.

![zero_20200406_182928](https://user-images.githubusercontent.com/25895405/78549296-b6479b00-7834-11ea-8ee2-685d96b46e94.png)

I want to write a plugin that the user can enter his configuration information.

> I already searched some plugins for helping. But they were written by `C#`.

**Comment by jjw24** [comment]
I am not sure how in Python, guess the original Wox documentations didn't help?

Maybe you can look at some of the other plugins written in Python if their authors able to do it. 

If I get time to play around with it, will let you know here/ if anyone else knows will be much appreciated.

**Comment by jjw24** [comment]
Just going to close this as this repo is no longer maintained, feel free to open the issue in Flow if this is still a problem
