### ISSUE TITLE
Delay when opening gsheet or gdoc files

### ISSUE THREAD

**Issue by mickdewald** [jjw24/Wox#180]
There is a noticeable delay of about 5 seconds when opening Google Docs documents from the moment I press enter until the document appears in the browser. I tested this with the newest Microsoft Edge browser (Version 80.0.361.111 (Official build) (64-bit)).  

This is not a serious problem, but it's not convenient cause everything else opens instantly. If I open a hyperlink to the same document it open instantly as well. Unfortunately I cannot see any problem, that might cause this, that is why I can't provide any further information at this point.

Tested on Windows 10 64 Bit with Wox JJW24 1.51.23

**Comment by mickdewald** [comment]
This does not seem to be a problem with Wox. It happens as well if I click on the gsheet  or gdoc file as well. I am sorry the inconvenience.

**Comment by jjw24** [comment]
All good, no worries at all
