### ISSUE TITLE
Set topmost result for query: Where to add?

### ISSUE THREAD

**Issue by skjerns** [jjw24/Wox#181]
I have set some applications as topmost for a certain query. 

1) How can I undo that?
2) How can I manually set certain keywords to show topmost results for something? If I type "code", 'Visual Studio Code' doesnt even get displayed and I'd like to start it like that.

**Comment by jjw24** [comment]
hey how's it going. 

1. You can undo it the same way you set it, shift + enter on the same query and result will show:
'Cancel topmost in this query'

2. Typing "code" and visual studio code is not showing is a known and raised issue here https://github.com/jjw24/Wox/issues/163. I will put out a fix soon.

**Comment by skjerns** [comment]
haha, funny that this is exactly the problem I'm having. Sorry that I didnt searhc.
