### ISSUE TITLE
"Win + R" activates Wox

### ISSUE THREAD

**Issue by cmbail** [jjw24/Wox#183]
### Steps to reproduce

1. Install Wox by download all files at https://github.com/jjw24/Wox/releases/tag/JJW24-v1.51.23, move files to directory, run Wox-JJW24-1.51.23.exe
2. Confirm Hotkey is default (Alt + Space)
3. Press Win + R

### Detailed logs
[2020-04-14.txt](https://github.com/jjw24/Wox/files/4476901/2020-04-14.txt)

### Screenshots (optional)
N/A

### Observed behavior
Wox activates

### Desired behavior
Windows Run dialog appears (my specific use case is I want to open Explorer at C:\Portable with [Win + R, \Portable, Enter])

**Comment by jjw24** [comment]
Can you check if you have this option ticked in settings:
![image](https://user-images.githubusercontent.com/26427004/79279238-e5bf6d00-7ef0-11ea-8a5f-08048352a96d.png)

This option is turned on by default, feel free to turn it off and you should get Win R back.

For your desired behaviour, you can add that directory to Folder plugin and it should appear (or you trigger with the plugin hotkey) without you needing to open Windows Run dialog and type in the path.

**Comment by jjw24** [comment]
Closing this issue. If still have questions please do not hesitate to reopen.
