### ISSUE TITLE
Portable update ᴏʙsᴛɪɴéᴍᴇɴᴛ won't copy user data 🐛

### ISSUE THREAD

**Issue by JustACuteGirlLookingForAManToFixHerBugs** [jjw24/Wox#184]
Hello, fellow coding people!

As you _(for some reason)_ might recall, I've tried the portable option introduced in JJW24-v1.50.23. Now, Wox is trying to update to JJW24-v1.51.23 and fails to do it properly both on my Laptop & PC.

1. Click check for updates (on Laptop it was on auto, on PC I clicked manually)
2. "Please restart Wox for the update". _I comply, but does Wox treat me the same way?.._ 😔
3. _Uh oh!_ Array of errors:
![2020-04-15 01-37-55](https://user-images.githubusercontent.com/9111191/79281178-e63d1100-7eba-11ea-9e52-e87c1595fe45.png)

4. It updates, but no settings are saved. And my browser bookmarks plugin is gone.

Logs in the 1.50.23 folder:
[2020-04-15.txt](https://github.com/jjw24/Wox/files/4478170/2020-04-15.txt)

Logs in the 1.51.23 folder:
[2020-04-15.txt](https://github.com/jjw24/Wox/files/4478167/2020-04-15.txt)

ChipmunkSetup log:
[SquirrelSetup.log](https://github.com/jjw24/Wox/files/4478173/SquirrelSetup.log)

```
function requestBugfix (politeness) {
  display(politeness + 'fix bugs!');
  nobleCodePersonOfColor.fixBugs;
  return(bugfix); }
requestBugfix ('please');
```

**Comment by JustACuteGirlLookingForAManToFixHerBugs** [comment]
`pleasefix bugs`

That's a joke, but also I'm pointing out that the error massage says 'manuallymove your profile'

**Comment by JustACuteGirlLookingForAManToFixHerBugs** [comment]
`pleasefix bugs`

This joke is meant to point out that the error massage says 'manuallymove your profile'

**Comment by JustACuteGirlLookingForAManToFixHerBugs** [comment]
`pleasefix bugs!`

This joke is meant to point out that the error massage says 'manuallymove your profile'

**Comment by JustACuteGirlLookingForAManToFixHerBugs** [comment]
`pleasefix bugs!`

😐
😐
😐

This is meant to point out that the error massage says 'manuallymove your profile'

**Comment by jjw24** [comment]
Hey thanks for the submit. This will be fixed in the new launcher.

I suspect the error is local to your computer, can you try this in the Windows Sandbox?

Will close for now. Happy to reopen if issue persists.
