### ISSUE TITLE
Wox 2 won't portablate itself

### ISSUE THREAD

**Issue by JustACuteGirlLookingForAManToFixHerBugs** [jjw24/Wox#185]
I feel like I create too many issues **ᵐʸ ᵉˣ ᵘˢᵉᵈ ᵗᵒ ˢᵃʸ ᵗʰᵃᵗ ᵃ ˡᵒᵗ**

But, well, I've tried to install the newest secret version, and it says
![image](https://user-images.githubusercontent.com/9111191/79284345-0b358200-7ec3-11ea-97d3-22d5a0b59236.png)

but here it is, cmon
![image](https://user-images.githubusercontent.com/9111191/79284357-11c3f980-7ec3-11ea-8df6-3808682c656d.png)

[2020-04-15.txt](https://github.com/jjw24/Wox/files/4478298/2020-04-15.txt)

**Comment by jjw24** [comment]
Just going to close this as this repo is no longer maintained, feel free to open the issue in Flow if this is still a problem
