### ISSUE TITLE
Developments and new updates

### ISSUE THREAD

**Issue by jjw24** [jjw24/Wox#186]
Hope everyone is safe and well.

Focus is now shifted over to the new launcher to get it off the ground, so you may not see many updates to this fork but they will be added to the new launcher instead.

Please feel free to continue to suggest new features and critical bug fixes via issues in this fork, they will be included in the new launcher or added to this fork if critical.

Once the new launcher is stable, everyone using this fork's Wox will be transitioned across to the new launcher via an update. So do not worry, you are not been left behind.

**Comment by cpkio** [comment]
The first thing I'd like to mention is easyness of theming. XAML is not a workhorse for most users, so creating a theme from scratch by hand is not easy. Colors and padding editing controls would be enough for most users, but width and height of input window would be nice too. Ot there should be an easily available big selection of themes.

Testing the recent «cleartype» build I noticed this portable version didnt catch up the start menu links. What I'd like to see is a plugin (?) allowing to manually add directories where the links would be searched, since I keep a personal directory of .lnk files in a directory additional to start menu.

**Comment by jjw24** [comment]
> Testing the recent «cleartype» build I noticed this portable version didnt catch up the start menu links. What I'd like to see is a plugin (?) allowing to manually add directories where the links would be searched, since I keep a personal directory of .lnk files in a directory additional to start menu.

I remmeber this is a bug in Wox, I noticed it way back when I was working on the program load but think it fell off the radar somewhat. Will patch that up soon.

**Comment by jjw24** [comment]
BTW @cpkio you already can add your personal directory of .lnk files in:
![image](https://user-images.githubusercontent.com/26427004/80274785-39675d00-8720-11ea-8fcd-ef41ba9d0add.png)

Let me know if this doesnt work

**Comment by cpkio** [comment]
@jjw24 this plugin was not included in the cleartype build you released, and I forgot about it existed in earlier versions since I dont use 'em. Thanks for explanation, will wait for a stable cleartyped release with this plugin.

**Comment by cpkio** [comment]
@jjw24 this plugin was included in the cleartype build you released, but it does not load for some reason, and I forgot about it existed in earlier versions since I dont use 'em now. Thanks for explanation, will wait for a stable cleartyped release with this plugin enabled.

**Comment by jjw24** [comment]
> @jjw24 this plugin was included in the cleartype build you released, but it does not load for some reason, and I forgot about it existed in earlier versions since I dont use 'em now. Thanks for explanation, will wait for a stable cleartyped release with this plugin enabled.

It is now released in the new version. In the File Suffixes button does it have extension 'lnk'. If still doesn't work let's take this conversation to a new issue instead.

**Comment by pc223** [comment]
> Focus is now shifted over to the new launcher to get it off the ground

So excited :smile: 

What is your plan for the new launcher?

Any chance for more flexible plugin support?
 IMHO the plugins system right now feel a bit "tight",  I'm thinking of a plugin manager that give more control for the plugin. Because sometimes plugin query really slow (web search) and need time to **dynamically update the view**, sometimes it fast enough to update the view right away. 

Plugins should able to control when plugin actually make the query, and when to response back. Sometimes plugins can make query every keypress but sometimes it have to wait a bit to avoid spamming the server.

I'm thinking of a more decoupled plugin system, dynamically update view from plugin, the plugin knows every events happen (keypress, mouse mouse movement,...) and update the views base on those :smile:

**Comment by jjw24** [comment]
> > Focus is now shifted over to the new launcher to get it off the ground
> 
> So excited 😄
> 
> What is your plan for the new launcher?
> 
> Any chance for more flexible plugin support?
> IMHO the plugins system right now feel a bit "tight", I'm thinking of a plugin manager that give more control for the plugin. Because sometimes plugin query really slow (web search) and need time to **dynamically update the view**, sometimes it fast enough to update the view right away.
> 
> Plugins should able to control when plugin actually make the query, and when to response back. Sometimes plugins can make query every keypress but sometimes it have to wait a bit to avoid spamming the server.
> 
> I'm thinking of a more decoupled plugin system, dynamically update view from plugin, the plugin knows every events happen (keypress, mouse mouse movement,...) and update the views base on those 😄

Plugin system will be one of the strong focus for the new launcher. At the moment we are still setting things and fine tuning a bunch of things. The first phase in working the plugin space is to make it easier for users to develop and release plugins for the new launcher to use, but I will keep your suggestions in mind once we are ready to move into the next phase.

**Comment by pc223** [comment]
> > > Focus is now shifted over to the new launcher to get it off the ground
> > 
> > 
> > So excited 😄
> > What is your plan for the new launcher?
> > Any chance for more flexible plugin support?
> > IMHO the plugins system right now feel a bit "tight", I'm thinking of a plugin manager that give more control for the plugin. Because sometimes plugin query really slow (web search) and need time to **dynamically update the view**, sometimes it fast enough to update the view right away.
> > Plugins should able to control when plugin actually make the query, and when to response back. Sometimes plugins can make query every keypress but sometimes it have to wait a bit to avoid spamming the server.
> > I'm thinking of a more decoupled plugin system, dynamically update view from plugin, the plugin knows every events happen (keypress, mouse mouse movement,...) and update the views base on those 😄
> 
> Plugin system will be one of the strong focus for the new launcher. At the moment we are still setting things and fine tuning a bunch of things. The first phase in working the plugin space is to make it easier for users to develop and release plugins for the new launcher to use, but I will keep your suggestions in mind once we are ready to move into the next phase.

Hopefully It'll have good integration with a scripting language like Python or Javascript, I think it's gonna be more convenient for plugin maker (and even end-user!) to develop, testing, debugging plugins. Right now, to setup a dev environment for plugins takes a lot of time.

**Comment by maholli** [comment]
**Very** excited for this. 🎉

Let us know when we can start testing and developing plugins @jjw24! I've stopped making personal plugins for Wox and started keeping a list so I can get the most out of my time-invested :)

**Comment by pc223** [comment]
I dream of a day when I can do things like google image search directly on Wox (native views not browser) :smile: It's gonna be really cool!

**Comment by jjw24** [comment]
A look at the new launcher in progress:
![The Flow](https://user-images.githubusercontent.com/26427004/82151677-fa9c7100-989f-11ea-9143-81de60aaf07d.gif)

**Comment by maholli** [comment]
> 
> 
> A look at the new launcher in progress:
> ![The Flow](https://user-images.githubusercontent.com/26427004/82151677-fa9c7100-989f-11ea-9143-81de60aaf07d.gif)

Looks fantastic! Very tactile and responsive. Must be on a private repo? Let us know when we can start tearing into it :)

**Comment by jjw24** [comment]
Update to get Flow Launcher 1.6.0

You may get a notice that your external Wox plugin can not be loaded in Flow. If this is the case, delete that plugin from your user data directory and then from Flow, search `pm install` + your plugin name. If it is not on the list, feel free to request a port [here](https://github.com/Flow-Launcher/Flow.Launcher/issues/170)
