### ISSUE TITLE
Feature: index windows settings

### ISSUE THREAD

**Issue by giggio** [jjw24/Wox#189]
### Are you submitting a bug report?

No

There should be a way to index Windows settings. For example, if I click on the Windows button and type `vpn`, Windows shows me vpn settings:

![vpn search windows](https://user-images.githubusercontent.com/334958/80309801-93faca80-87ad-11ea-9b4f-f1c94e5affed.png)

This does not work with Wox.

This is similar from https://github.com/Wox-launcher/Wox/issues/2223, but using `> ms-settings:network-vpn` on Wox also does not work, and it is not searchable.
You get `The filename, directory name, or volume label syntax is incorrect.`.

**Comment by jjw24** [comment]
Just going to close this as this repo is no longer maintained, feel free to open the issue in Flow if this is still a problem
