### ISSUE TITLE
[Suggestion] [Low priority] A portable (dot zip file) release is more intuitive (and convenient) for portable user

### ISSUE THREAD

**Issue by pc223** [jjw24/Wox#190]
This is not a huge thing, but if it's not take too much of your time, I think a portable zip file release is more intuitive (and convenient) for portable user :smile: (compare to let .exe file extract itself, and copy it around)

**Comment by jjw24** [comment]
So we have the proper portable mode now, which you can trigger from the settings menu. Once it's in portable mode you can move it around, and for new updates you can directly trigger the update via query or from settings menu, and the update will update the launcher even if it is in portable mode. This means you dont have to redownload the exe everytime there is an update.

**Comment by pc223** [comment]
> So we have the proper portable mode now, which you can trigger from the settings menu. Once it's in portable mode you can move it around, and for new updates you can directly trigger the update via query or from settings menu, and the update will update the launcher even if it is in portable mode. This means you dont have to redownload the exe everytime there is an update.

Personally, I still like the "standard" way of doing portable program more, just one zip file, and **done**, no need to config anything. Right now, after I downloaded the .exe file, I have to do a bit of config, and copying things around, a little bit messy, compare to good old zip release :smile:

**Comment by jjw24** [comment]
> Personally, I still like the "standard" way of doing portable program more, just one zip file, and **done**, no need to config anything. Right now, after I downloaded the .exe file, I have to do a bit of config, and copying things around, a little bit messy, compare to good old zip release :smile:

Hmm not 100% sure what you mean. Wouldn't you just need to down the exe once install configure, enable portable mode. Then move it where ever you want. You can keep the program up to date either via auto updates or manually. You wouldn't need to redownload the exe again and reinstall, or have I missed something sorry?

**Comment by pc223** [comment]
> > Personally, I still like the "standard" way of doing portable program more, just one zip file, and **done**, no need to config anything. Right now, after I downloaded the .exe file, I have to do a bit of config, and copying things around, a little bit messy, compare to good old zip release 😄
> 
> Hmm not 100% sure what you mean. Wouldn't you just need to down the exe once install configure, enable portable mode. Then move it where ever you want. You can keep the program up to date either via auto updates or manually. You wouldn't need to redownload the exe again and reinstall, or have I missed something sorry?

Yeah, the thing is the first step after download the .exe file is we have to open it up, and config it, and move the appdata folder (from a obscure location, not many user know where to look) to a different location (Like my USB). Compare to zip release, we extract it to a folder, and done, no config needed :smile: 

I mean that's the "standard" way that many portable software release that way, no dependencies on auto-update, just a simple, "download, extract, and execute" workflow.

**Comment by jjw24** [comment]
Haha OK fair enough. Maybe in the future we can consider having something from the exe to extract to a given location if for portable is selected.

**Comment by jjw24** [comment]
Just going to close this as this repo is no longer maintained, feel free to open the issue in Flow if this is still a problem
