### ISSUE TITLE
[Suggestion] [Plugin.Program] Support for .url shortcut file (like csgo, dota)

### ISSUE THREAD

**Issue by pc223** [jjw24/Wox#191]
Right now _the Program plugin_ doesn't register shortcut like csgo shortcut, because it is `.url` shortcut not `.lnk`

I did hack together this code for my personal use (I don't know much C# so I'm _not_ making a pull request), hopefully it can be helpful. 
My changes in Wox.Plugin.Program: https://github.com/jjw24/Wox/compare/master...thanhmssl10:urlshortcut

Shortcut have .url extension:
![image](https://user-images.githubusercontent.com/10551242/81062824-e4d29780-8f00-11ea-83cc-7154215a48e7.png)

Wanted result:
![image](https://user-images.githubusercontent.com/10551242/81063261-b5705a80-8f01-11ea-85c5-15d52c904e2c.png)

**Comment by jjw24** [comment]
does it not work if you add the extension in program plugin via File Suffixes?

**Comment by pc223** [comment]
> does it not work if you add the extension in program plugin via File Suffixes?

Oh yeah, I forgot, let me get back to you, I got this problem like 6 months ago, not tested on the new releases :smile:

**Comment by pc223** [comment]
@jjw24 Update

Add `;url` to File Suffixes doesn't work because the function `StartMenuPrograms()` only return programs that  the files have extension `.lnk` and `appref-ms` (hard-coded).

And the function `LnkProgram()`, I pretty sure it cannot handle `.url` files (I remember it throws some errors but I don't remember exactly what errors 😅). In my code, I have to use different code to read the `.url` file, can't reuse `LnkProgram()`

![image](https://user-images.githubusercontent.com/10551242/82747440-ed611400-9dc2-11ea-9731-1f1170bc614d.png)

**Comment by jjw24** [comment]
Just going to close this as this repo is no longer maintained, feel free to open the issue in Flow if this is still a problem
