### ISSUE TITLE
Docker Desktop exe not displayed

### ISSUE THREAD

**Issue by skjerns** [jjw24/Wox#192]
I Installed Docker Desktop for Windows.

However the starter shortcut does not get indexed. It's located at `C:\ProgramData\Microsoft\Windows\Start Menu` 

It seems like only `C:\ProgramData\Microsoft\Windows\Start Menu\Programs` is indexed. Maybe the indexing should be changed to also include the parent?

**Comment by jjw24** [comment]
Yeah I ran into that in the past as well, maybe we should index that level instead, although I don't quite get why there is 'Start Menu' and then there is 'Start Menu\Programs', what's the difference?

Until the fix, you should be able to move it to Programs or add that location in and unchecked start menu.

**Comment by jjw24** [comment]
Just going to close this as this repo is no longer maintained, feel free to open the issue in Flow if this is still a problem
