### ISSUE TITLE
Add Hook magic

### ISSUE THREAD

**Issue by Zeroto521** [jjw24/Wox#194]
Will Wox adds some **hook** magic? I thought it could get great!

Think about these situations.
- The user installs the plugin, the plugin can do something at the same time.
- The user launches the plugin, the plugin can do something at the same time.
- ...

There are a lot of applications.
Actually the `query` function is too heavy.
Hook magic can help us.

**Comment by jjw24** [comment]
This is an interesting idea indeed!

**Comment by jjw24** [comment]
just going to close this as this repo is no longer maintained, feel free to open the issue in Flow
