### ISSUE TITLE
A Python Template Advice for Wox plugin

### ISSUE THREAD

**Issue by Zeroto521** [jjw24/Wox#195]
I have concluded some useful advice or experiences for me to write a good Wox plugin.

So I want to share it to guys. And this project I called [Wox.Plugin.PythonTemplate](https://github.com/Zeroto521/Wox.Plugin.PythonTemplate).

That project is a Python Template Advice for Wox plugin, not a plugin. 

From this project, Python developer can solve some problems like **language localization**, **command**, **structure code**, and so on.

[Wox.Plugin.Timestamp](https://github.com/Zeroto521/Wox.Plugin.Timestamp) is a example under that template.

Hope guys like.

**Comment by jjw24** [comment]
Hey thank you for this. I will take a look at the template advice soon and discuss further. 

This fork will no longer receive development unless it's a critical fix. 

I have moved your issue over at Flow Launcher which is under heavy development. We are also looking to up our Python plugin documentation. So lets take our discussions over there. https://github.com/Flow-Launcher/Flow.Launcher/issues/157
