### ISSUE TITLE
Wox.Plugin.Shell- Option to run scripts in either CMD or PS

### ISSUE THREAD

**Issue by jjw24** [jjw24/Wox#2]
Currently it's a toggle in the plugin's settings menu. Instead, allow user to run command in either PS or Cmd without haven't to change it in settings every time.

**Comment by HsunGong** [comment]
I think there can exists 2 results, one for cmd, the other for PS, rather than set this in `settings` page.

**Comment by jjw24** [comment]
Yeah am thinking like how it's set up in WebSearch plugin, can use hotkey to trigger them.

**Comment by jjw24** [comment]
Just going to close this as this repo is no longer maintained, feel free to open the issue in Flow if this is still a problem
