### ISSUE TITLE
Conversation(交流贴)

### ISSUE THREAD

**Issue by HsunGong** [jjw24/Wox#32]
Happy to see you are still updating this project!!!!!!!!!!!!!!!!!

Can you establish `releases`, so we can use your update version???
That's nice to me.

By the way, have you got connections of contributors of `wox`? Seems they've gone.

**Comment by jjw24** [comment]
Hi there,

Yes I am still actively updating this project.

I have released this fork's version of updated Wox along with many enhancements I made, you can download it here: https://github.com/jjw24/Wox/releases/tag/v1.3.524%2BJJW24.v1.12.2

I have not gotten in touch with the contributors of Wox, hopefully they are still updating the project though the last merge was a while back.

Regards

**Comment by HsunGong** [comment]
The portable version works well in my Win10.

**Comment by pc223** [comment]
Thanks for all these fixes and enhancements, I got to try your release now! :smile:

**Comment by jjw24** [comment]
Pleasure. Enjoy :)

**Comment by r3db34rd0** [comment]
Thank you very much for your work!

**Comment by mmqmzk** [comment]
Does the Plugin BrowserBookmark support third-party chromium browsers? I installed Firefox and CentBrowser on my computer, and use CentBrowser as my default browser, BorwserBookmark plugin only searches Firefox bookmarks. Maybe it's better to let users choose search in which browser's bookmarks.

**Comment by jjw24** [comment]
> Does the Plugin BrowserBookmark support third-party chromium browsers? I installed Firefox and CentBrowser on my computer, and use CentBrowser as my default browser, BorwserBookmark plugin only searches Firefox bookmarks. Maybe it's better to let users choose search in which browser's bookmarks.

Hey how's it going. 

Currently Wox doesnt support Chromium browsers (but I am not sure if there are plugins out there that do, at least this default one that is packed with Wox doesn't).

In the browserbookmark plugin you can choose which browser to search the bookmarks from by setting the path to the browser executable:
![image](https://user-images.githubusercontent.com/26427004/70607963-78a27f00-1c53-11ea-8767-cc614be6f59a.png)
However it only supports searching for bookmarks in Firefox or Chrome.

Bookmark search code differs depends on which browser it is if i remember correctly so for every browser's bookmark that we want to support we have to build it in, it is not transferable.

**Comment by mmqmzk** [comment]
Thanks for the reply. Most chromium browsers have the same mechanism of storing bookmarks like chrome (in a JSON file `Bookmark`), and have similar files structure (at least CentBrowser is), maybe the bookmark search plugin just need some path configuring.

**Comment by jjw24** [comment]
> Thanks for the reply. Most chromium browsers have the same mechanism of storing bookmarks like chrome (in a JSON file `Bookmark`), and have similar files structure (at least CentBrowser is), maybe the bookmark search plugin just need some path configuring.

Sure thing put it through as a feature request and see if have time to build it in or maybe someone else will be able to help out too.

**Comment by cpkio** [comment]
I was using UELI, and recently found WOX and this fork. What repels me from using it is low display quality — WOX uses not cleartype, but some other font smoothing. The fonts look ugly. It this because of UWP usage or you can make some tweak and enable cleartype smoothing?

**Comment by jjw24** [comment]
> I was using UELI, and recently found WOX and this fork. What repels me from using it is low display quality — WOX uses not cleartype, but some other font smoothing. The fonts look ugly. It this because of UWP usage or you can make some tweak and enable cleartype smoothing?

Yeah Wox's visual can definitely get some refining, put this cleartype request as a feature and will see if there is time to play with the font rendering.

**Comment by HsunGong** [comment]
> Thanks for the reply. Most chromium browsers have the same mechanism of storing bookmarks like chrome (in a JSON file `Bookmark`), and have similar files structure (at least CentBrowser is), maybe the bookmark search plugin just need some path configuring.

From https://github.com/jjw24/Wox/issues/32#issuecomment-564467698, here is a plugin **[hindsight](https://github.com/obsidianforensics/hindsight.git) ** for chrome, and I don't know if it works. A plugin can be designed by your self to read the excel. 
However, it costs if you'd like to use this tool to update your bookmarks everytime you want to search them.

**Comment by Ciantic** [comment]
Hey! Great just found this fork.

First issue, it doesn't start, it just flashes in the task bar. Maybe some issue with old config, will debug more. I don't expect answer here. Just wanted to give thumbs up for the effort.

P.S. It started working after I deleted `%appdata%\Wox`.

**Comment by jjw24** [comment]
For a better experience, update to get [Flow Launcher](https://github.com/Flow-Launcher/Flow.Launcher) 1.6.0
