### ISSUE TITLE
Wox JJW24.v1.14.3 fail to startup, throw AccessViolationException and a possible fix

### ISSUE THREAD

**Issue by pc223** [jjw24/Wox#44]
So the release [v1.3.524+JJW24.v1.14.3](https://github.com/jjw24/Wox/releases/tag/v1.3.524%2BJJW24.v1.14.3), when running at my computer can't startup, the icon at system tray disappears after around 10 seconds, this is the log: [wox-log.txt](https://github.com/jjw24/Wox/files/3676849/2019-10-01.txt)

I tried to build from your source code and get `AccessViolationException` at [FirefoxBookmarks.cs:35](https://github.com/jjw24/Wox/blob/ce9f2157e8c3776bf3dd45db6984bec0da223435/Plugins/Wox.Plugin.BrowserBookmark/FirefoxBookmarks.cs#L35)

[AccessViolationException - screenshot](https://user-images.githubusercontent.com/10551242/65971113-e7b06a00-e491-11e9-9b91-3c014e9d5e56.png)

So I tried to delete the plugin `Wox.Plugin.BrowserBookmark` and now Wox can startup and function normally. 

After a bit messing around, I find out that the `System.Data.SQLite.dll` ship with your release is version `1.0.93.0`, which is older than the lib be shipped with official BrowserBookmark on Wox.one (`1.0.102.0`). So I change the reference in VS2015 to the newest version of System.Data.SQLite.dll and Wox now functions normally with FirefoxBookmarks enabled.

So I guess the problem is `System.Data.SQLite.dll` `1.0.93.0` doesn't work with newer **firefox**, I use **firefox 69.0.1**, and **Windows 8.1**, all **64-bit.**

Changes:
https://github.com/jjw24/Wox/compare/master...thanhmssl10:fix-access-violation

**Comment by jjw24** [comment]
Hey @thanhmssl10, thanks for the find and investigation. I personally don't use Firefox so wouldn't have come across this bug. I have added in the change as a pull request. 

I am not able to replicate your issue with Firefox (same Firefox version but on Windows 10) and come across another issue where the Firefox bookmarks are not showing up at all with the current release. So I have released your bug fix as a pre-release, and will investigate a bit more on the bug that I came across.

Please test out the new build [here](https://github.com/jjw24/Wox/releases/tag/Wox-v1.3.524%2BJJW24.v1.14.4) and let me know if it fixes this issue.

**Comment by pc223** [comment]
Your new build works perfectly :+1: FirefoxBoomarks feature works

If you can't replicate the issue, I can help, although I don't know much of C#, but  I have setup a dev environment, you can send me test cases or instructions to further investigation 😃

**Comment by jjw24** [comment]
Hey thanks for the offer. So far all good, I have replicated the issue and know why it is causing an access violation. If you are interested you can check out the description in the referenced PR.

Also found out why Firefox bookmarks are not showing up for me. The code in BrowserBookmarks plugin looks for an incorrect attribute in the profile.ini file. I will put up a PR to fix the code later on, and get you to test if it is OK.

**Comment by pc223** [comment]
> It will throw an System.AccessViolationException due to the incorrect sqllite dll included where the plugin is expecting sqllite dll version 1.0.93 and the version embeded is actually 1.0.102.

So if I understand correctly, 1.0.93 and 1.0.102 both can work with Firefox 69.0.1? Although the version in `packages.config` have to match with the lib being reference? :thinking:

**Comment by jjw24** [comment]
Usually if the dll version does not match packages.config, the project may not complain during compile and build , but when it comes to actual run time the behavior may not be what you had expected. In this instance it throws an access violation.

I think 1.0.93 may work with Firefox 68.0.1 but can't prove it because NPM no longer restores that sqlite version probably because it is no longer supported.

The new pre-release is here(https://github.com/jjw24/Wox/releases/tag/v1.3.524%2BJJW24.v1.14.5), please test it and let me know if your Firefox bookmarks are still good.
