### ISSUE TITLE
Executable plugin init section

### ISSUE THREAD

**Issue by r3db34rd0** [jjw24/Wox#47]
Hello, thank you for your work.
Can you please tell me, it is possible to do the init section that is executed when Wox is loaded, if I use my plugin as standalone exe file?

**Comment by jjw24** [comment]
Hi there, not sure what you mean by init section, but if i understand correctly, you want to run only your plugin and as a standalone.

The way Wox is designed, you can add/delete any plugin project in the 'Plugins' folder as it contains only plugins. Other projects outside of that folder such as Wox.Core, Wox.Infrastructure are essential. So there are possible two was of doing it:

1. From what I have read you can use NPM to add Wox.Plugin package into your plugin project. However I have tried that but on first attempt it complained about missing Wox.Infrastructure project. I think you can solve this by add the Infra project in manually as it is not published in NuGet. 

    There is a repo floating in Github somewhere I have come across in the past where the owner made Wox plugin skeleton that can run as a standalone, but I dont remember who the author is now, you should be able to find it with a search.  

2. Remove the existing plugins in the Wox project and just add yours in. It is a bit of pain to do but it would work.

**Comment by r3db34rd0** [comment]
Thank you for the answer.
I meant this. From the documentation
http://doc.wox.one/en/plugin/csharp_plugin.html

> Init method will be invoked when Wox loading this plugin. You can do some preparations here. PluginInitContext paramter will provide some public API you can use and other userful objects. 

And here's the python plugin documentation
http://doc.wox.one/en/plugin/python_plugin.html
I don't see any init sections here, i.e. nothing happens at the start of the wox.

I want to write my own plugin like here:
https://github.com/Wox-launcher/Wox/issues/2409

Can I do init for the last option?

**Comment by jjw24** [comment]
Do you mean something like:
```
def __init__(self):
    #initsomestuff

def query(self, query):
    #returnresultobject
```
Apologies if I am still not answering your question.

**Comment by r3db34rd0** [comment]
Yes, something like this, but how to write it for standalone exe plugin?

**Comment by jjw24** [comment]
hmm sorry I can't help you here I haven't had time to play around with a standalone

**Comment by r3db34rd0** [comment]
Okay, thank you and good lock!

**Comment by HsunGong** [comment]
If you develop a CSharp plugin, maybe it is a good idea to track in `VS`.

In my opinion, a plugin should not use a `init` step during `Wox` startup. Reasons are as follows: (1) We do not use the plugin all the time as the main wox process, so each time init plugin is not a costy problem. (2) If your plugin needs `init` in startup, it means `init` need a lot of resources, which will employ a lot of mem and bad to your computer. You can set a query to do all `init` and store in disk. Once you need it, load the database from disk.

Comments are for reference only.

**Comment by jjw24** [comment]
Just going to close this as this repo is no longer maintained, feel free to open the issue in Flow if this is still a problem
