### ISSUE TITLE
Wiki Wanted

### ISSUE THREAD

**Issue by HsunGong** [jjw24/Wox#48]
We can use everything API's **regular expression** with **prefix** `@`

About [`Everything API`](https://github.com/jjw24/Wox/tree/master/Plugins/Wox.Plugin.Everything)

The execution path is
- [Main.cs get api](https://github.com/jjw24/Wox/blob/ce9f2157e8c3776bf3dd45db6984bec0da223435/Plugins/Wox.Plugin.Everything/Main.cs#L45)
- [Everything API get search function](https://github.com/jjw24/Wox/blob/ce9f2157e8c3776bf3dd45db6984bec0da223435/Plugins/Wox.Plugin.Everything/Everything/EverythingAPI.cs#L186)
![image](https://user-images.githubusercontent.com/32933986/66184175-dcd22100-e6ad-11e9-826c-b448ecc1cfb1.png)

**Comment by jjw24** [comment]
I have opened up Wiki section in this fork so feel free to contribute if you want to expand on the above.
