### ISSUE TITLE
Wox failed to start up after updating Win 10 to lastest patch

### ISSUE THREAD

**Issue by kurokeita** [jjw24/Wox#56]
### Are you submitting a bug report?

Yes

### Steps to reproduce

1. Update Win 10 to the lastest cumulative patch (KB4517389)
2. Start Wox
3. It starts then crash immediately, no error prompt

### Detailed logs
[2019-10-14.txt](https://github.com/jjw24/Wox/files/3723593/2019-10-14.txt)

### Screenshots (optional)
No error prompt appears so there are no screenshot

### Tried:
1. Reinstall -> didn't work
2. Delete Wox folder in %APPDATA%\ -> didn't work
3. Uninstall the Windows's update patch -> worked

**Comment by jjw24** [comment]
Hey there, hows it going.

Thanks for the report. I have not yet updated my win 10 to the latest. I will do so in the next couple of days and debug it.

Thanks for the report.

**Comment by kurokeita** [comment]
Thanks for your prompt reply, guess I will uninstall the update patch and wait for you :D

**Comment by jjw24** [comment]
Yes, that should get Wox working for now. I am in the middle of developing something else so will not be able to update my machine straight away.

Initial glance from your log file it's the Program plugin that's throwing the error when it is trying to load your programs. Microsoft may have changed something with the update. Deleting out the Program plugin (not tested) theoretically could get Wox working if one really want to use Wox with the latest Win10 update.

**Comment by kurokeita** [comment]
Yeah, I noticed it too, but the funny thing is that the Program plugin is part of Wox's default plugins set so I can not disable it without opening Wox first and go to setting->plugins. But then, I can not open Wox at all, its icon would just show in the system tray for like 10 seconds then disappear

**Comment by jjw24** [comment]
I just updated two machines to the latest win 10 version but I am not able to replicate the issue, Wox is starting up fine.

I did notice in your logs it looks loke you are using the upstream repo's Wox release 578. If that's the case can you uninstall Wox, as well as the Everything app and download this fork's release https://github.com/jjw24/Wox/releases/latest and let me know how you go.

**Comment by kurokeita** [comment]
I'm sorry for not mentioning that I'vs tried both your fork and the older release of the old Wox but all have the same crash. I'll try to uninstall Everything to test.

**Comment by jjw24** [comment]
Yeah let me know how you go with uninstalling Everything. 

Also, if it is possible, can you boot up Windows Sandbox and run Wox there. My reasoning is that this could be related to some app installed on your machine, sandbox should have minimal apps and barebones environment. 

I will test Wox on a couple other Win10 machines to see if it is indeed the update

**Comment by kurokeita** [comment]
I've tried uninstalling Everything but Wox still crashes on start. Then I tried using it in sandbox and it worked perfectly.
Here is the new log file: [2019-10-15.txt](https://github.com/jjw24/Wox/files/3727318/2019-10-15.txt)
I'm using the lastest release from your fork

**Comment by kurokeita** [comment]
Excuse me for asking again, but do you have any more new insight into this issue. After installed the update patch (KB4517389) again to test with Everything uninstalled and to test in sandbox, my computer now can't uninstall that patch and I'm stuck with it :(

**Comment by jjw24** [comment]
Hey all good, sorry I have yet to take a look at this issue further.  Due to other commitments I probably will not be able to do so until the week after the next.

If anyone else able to help out that would be greatly appreciated.

Having said that I will take a look and try to resolve once I am free. This is quite difficult to troubleshoot as I am not able to replicate the error on the conditions you outline above. In the mean time I can offer you hopefully a workaround. Not the best at all, but at least should get Wox running:

Delete out the Plugins.Programs folder which is located here: %localappdata%\wox\app-1.2.0\Plugins\Wox.Plugin.Program

This means you will not be able to query for programs installed on you computer, but at least will not cause exception when Wox tries to load up programs on your comp. I will see if I can get to the issue later on.

**Comment by jjw24** [comment]
Hey can you backup user data and uninstall your current Wox, download this release https://github.com/jjw24/Wox/releases/tag/v1.3.524%2BJJW24.v1.23.7 and run it as Administrator and attach the log if you are still getting an error please.

**Comment by kurokeita** [comment]
Hi, thanks for getting back to me, I uninstalled Wox and ran the newest release as Administrator but still got the same problem. Here is the log: [2019-10-27.txt](https://github.com/jjw24/Wox/files/3775502/2019-10-27.txt)

**Comment by jjw24** [comment]
Does it run if you delete the Plugins.Programs folder which is located here: %localappdata%\wox\app-1.2.0\Plugins\Wox.Plugin.Program?

**Comment by kurokeita** [comment]
No, I tried that with both as Admi an without as Admin

**Comment by jjw24** [comment]
So it doesnt run even after deleting the Wox.Plugin.Program folder?

**Comment by kurokeita** [comment]
Yes, I even tried to delete the whole plugins folder

**Comment by jjw24** [comment]
I see. Looks like it's Wox that's erroring out not the plugins as originally thought. I will need to build some more logging in to get a better picture as current logs is not descriptive enough and I am not able to replicate your issue. 

Will have to get back to you in a few days.

**Comment by HsunGong** [comment]
> Yes, I even tried to delete the whole plugins folder

Update to the newest versions of `Wox` of `v1.3.524+JJW24.v1.26.13` may help.(FIXed some issues in `program` plugin.)

Rollback to the oldest versions of `Wox` of `v1.3.524+JJW24.v1.12.2` may help.(No change in `program` plugin.)

**Comment by jjw24** [comment]
Wox has gone through several iterations. Closing this issue. Happy to reopen if persists.
