### ISSUE TITLE
Add option to open web results in existing browser window

### ISSUE THREAD

**Issue by EliSadaka** [jjw24/Wox#70]
### Are you submitting a bug report?

No

The behaviour of the plugins that open webpage results was changed so that they always open the results in a new browser window. I would like the option for it to be set to the previous behaviour where it would open a new tab if a browser window was already open.

**Comment by jjw24** [comment]
https://github.com/jjw24/Wox/releases/tag/v1.3.524%2BJJW24.v1.25.11
