### ISSUE TITLE
Feature: Add System Hardware Toggles (e.g., Toggle Bluetooth, Airplane mode, Night Light, etc.)

### ISSUE THREAD

**Issue by jjw24** [jjw24/Wox#79]
Per suggestion from https://github.com/Wox-launcher/Wox/issues/2642

@Kalaschnik
"I hide a lot of toggles in my action center to have clean look (that is just one use case). In anyway, it would be neat if there would be shortcut toggles for bluetooths, airplane mode, wifi, night light etc.

Thanks for considering

[EDIT]
Seems like they would have a good place in System Commands"

**Comment by HsunGong** [comment]
However, I think it is difficult to set easily in windows.

**Comment by jjw24** [comment]
Not sure, you might be right. Maybe only able to add a couple of the switches. Havent had the time to look into it, but definitely good feature to add in. They can live in the sys plugin.

**Comment by jjw24** [comment]
Just going to close this as this repo is no longer maintained, feel free to open the issue in Flow if this is still a problem
