### ISSUE TITLE
New Feature: Highlighting how results matched

### ISSUE THREAD

**Issue by SysC0mp** [jjw24/Wox#81]
Long-time ago,  @JohnTheGr8 created a pull request to add this feature to WOX. 
Unfortunately, the pull request was never merged and there have been so many changes that a new pull request would be needed.

Original pull request: [https://github.com/Wox-launcher/Wox/pull/977](https://github.com/Wox-launcher/Wox/pull/977)

In my opinion, this is a great feature and should be added.
I will try to pick out his changes and add them to this repository.

Let me know what you think about it. :)

**Comment by jjw24** [comment]
I think this will be a great add, will help further how users search. :+1:

**Comment by jjw24** [comment]
This feature is now added thank you @SysC0mp @JohnTheGr8
