### ISSUE TITLE
Feature: [Bookmark Plugin] Support third-party browsers and let users choose from multiple installed browsers.

### ISSUE THREAD

**Issue by mmqmzk** [jjw24/Wox#97]
### First

The default packed BookmarkPlugin only supports Firefox, chrome and the official build chromium. Since most third-party chromium browsers have similar mechanism storing bookmarks like chrome, in a JSON file named `Bookmark` in the `User Data` folder. I took a look into the source code and found [this block](https://github.com/jjw24/Wox/blob/f3a1e09042b06b7c293b8a6c795a5c3515db2d87/Plugins/Wox.Plugin.BrowserBookmark/ChromeBookmarks.cs#L78), just need to add the path to `User Data`, this plugin will support third-party chromium browsers. Maybe it is better to let users configure their browser's user data path rather than hardcoded. The same as third-party Firefox-based browsers.

### Second

It is usual to have multiple browsers installed on one computer, it is better to let users choose to search in which one or which ones browsers.

Sorry for I know little about C#. Could someone help? Or maybe I'll see what I can do later.

**Comment by HsunGong** [comment]
> ### First
> The default packed BookmarkPlugin only supports Firefox, chrome and the official build chromium. Since most third-party chromium browsers have similar mechanism storing bookmarks like chrome, in a JSON file named `Bookmark` in the `User Data` folder. I took a look into the source code and found [this block](https://github.com/jjw24/Wox/blob/f3a1e09042b06b7c293b8a6c795a5c3515db2d87/Plugins/Wox.Plugin.BrowserBookmark/ChromeBookmarks.cs#L78), just need to add the path to `User Data`, this plugin will support third-party chromium browsers. Maybe it is better to let users configure their browser's user data path rather than hardcoded. The same as third-party Firefox-based browsers.
> 
> ### Second
> It is usual to have multiple browsers installed on one computer, it is better to let users choose to search in which one or which ones browsers.
> 
> Sorry for I know little about C#. Could someone help? Or maybe I'll see what I can do later.

The first one seems to be solved. 
The second one, `choosing which browser to use` remains.

Here is a naive solution:
Change `Browser Bookmark` into another name, as `Chrome BB` and `FireFox BB`, and change keyword for them. 
> That means: create a copy of the original plugin, and change keywords to let these copies have different functions(with different user path). This is easy to achieve Target `Multiple browsers`.

**Comment by jjw24** [comment]
Hey how's it going. Sorry for the late feature add.

Browsing of Chromium Edge's bookmarks has been added to Flow Launcher https://github.com/Flow-Launcher/Flow.Launcher/pull/121 and will be released soon.

The second issue will be transferred to Flow's repo and worked on later. :)

**Comment by jjw24** [comment]
Closing this issue. For progress please visit the mentioned issue.
