### ISSUE TITLE
Feature: Improve calculator plugin

### ISSUE THREAD

**Issue by SysC0mp** [jjw24/Wox#99]
I was planning to add a couple of improvements to the calculator plugin.

- New setting to set the output decimal separator to either dot or comma. Currently, it is fixed to a dot. The current locale can be used as "default" here.
- Enable calculation with dot and comma. Currently, only dots are allowed as input value.
- Add new settings to set max calculation precision. 
- Solve rounding errors in a couple of circumstances. (Wox-launcher#2349)

This should also close issue Wox-launcher#2106

**Comment by jjw24** [comment]
@SysC0mp hey buddy, out of curiosity only, have you made any progress with this into a PR?

**Comment by RalfRoemling** [comment]
would be interested too

**Comment by SysC0mp** [comment]
Hey! 👋 I started implementing it, but i had no time yet to finish it up and test everything. Sorry for the long wait... :)
I'll try to finish that the next couple of days and create a PR for it.

**Comment by RalfRoemling** [comment]
👋 That'll be great. Thx 😄
